### ISSUE TITLE
.set("val").sparql may result in DELETE DATA query with variables

### ISSUE THREAD

**Issue by andrewzhurov** [LDflex/LDflex#352]
Paths, such as:
``` js
await path.create("http://example.com/subj1")
          .somePredicate
          .set("new value")
          .sparql
```
May result in DELETE DATA queries with variables, such as:
```sparql
DELETE DATA {
  <http://example.com/subj1> <http://example.com/somePredicate> ?somePredicate.
}
;
INSERT DATA {
  <http://example.com/subj1> <http://example.com/somePredicate> "new value".
}
```
Which is okay by LDFlex, as seen in [this test](https://github.com/LDflex/LDflex/blob/3379cb7059dccdfb41de804a2e0db338e974cc3a/test/integration/sparql-test.js#L240).

However, [as per the spec](https://hyp.is/Hy5sDu8nEe2aQ5s-MJcjyw/www.w3.org/TR/sparql11-update/), variables are not allowed in DELETE DATA queries, and other query engines that are more strictly conformant to the spec may fail to execute such queries, e.g., Comunica fails with:
```
SparqlParser.js:1193 Uncaught (in promise) Error: Detected illegal variable in BGP
    at Yr (SparqlParser.js:1193:19)
    at Object.performAction (SparqlParser.js:336:62)
    at tn.parse (SparqlParser.js:787:36)
    at Parser.d.parse (sparql.js:36:37)
    at s.run (ActorQueryParseSparql.ts:27:33)
    at s.runObservable (Actor.ts:83:37)
    at i.mediate (Mediator.ts:86:18)
    at async a.queryOrExplain (QueryEngineBase.ts:165:13)
    at async a.query (QueryEngineBase.ts:87:11)
    at async a.queryOfType (QueryEngineBase.ts:70:11)
```

Perhaps having such paths result in `DELETE ... WHERE ...` would make LDFlex more conformant with the spec and allow their execution by other engines.

Environment:
        "@ldflex/comunica": "^5.0.1",
                "ldflex": "^2.15.2",
                        "@comunica/query-sparql": "^2.6.9",

**Comment by andrewzhurov** [comment]
Hi, Jesse!
I wouldn't mind fixing it, for that I'd need to adjust the test, for that I'd need a working test workflow, and it fails for me at this moment. Same as on the CI. Any estimates on when it'll get patched?

**Comment by jeswr** [comment]
I'm happy for you to branch off [this commit](https://github.com/LDflex/LDflex/tree/c682b455e4f2b8fdb00021ee0073eb59c8dc8431) where CI is passing. The subsequent dependabot commits need to be reverted as the upgrade to @rdfjs/data-model v2 (which is ESM only) is what broke things in the first place.

**Comment by jeswr** [comment]
Once you create a PR I'll revert those commits on main, and manually do relevant upgrades once merging your work.

**Comment by andrewzhurov** [comment]
Also found the same story for INSERT DATA, from what I reckon [vars there are disalowed](https://hyp.is/DXQYRvlfEe2Wx5s1l20PVQ/www.w3.org/TR/2013/REC-sparql11-update-20130321/).
Will adjust that case as well.
